# Generated by Django 4.2 on 2024-03-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='templates/assets/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='image',
            field=models.ImageField(upload_to='templates/assets/images/'),
        ),
    ]
